---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://mrjesma.github.io/my-argocd/my-app-helm'
    targetRevision: 0.2.0
    chart: my-app-helm
    helm:
      parameters:
        - name: "image.tag"
          value: 1.19.0
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
