---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-kustomize-image-updater-git
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: airtonorlandini/nginx
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/mrjesma/my-argocd.git
    targetRevision: main
    path: my-app-kustomize/env/stage/my-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true


